// <auto-generated />
using System;
using Attendance.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Attendance.API.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    partial class AttendanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Attendance.API.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IdentityExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Attendance.API.Models.EmployeeAttendance", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BreakEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BreakStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClockInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClockOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("isOTClaimed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("EmployeeId")
                        .HasName("EmployeeAttendances_pkey");

                    b.ToTable("EmployeeAttendances");
                });

            modelBuilder.Entity("Attendance.API.Models.OfficeConfiguration", b =>
                {
                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("OfficeBreakDuration")
                        .HasColumnType("interval");

                    b.Property<string>("OfficeDescription")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OfficeEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("OfficeGracePeriod")
                        .HasColumnType("interval");

                    b.Property<string>("OfficeLicence")
                        .HasColumnType("text");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OfficeStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OfficeId");

                    b.ToTable("OfficeConfigurations");
                });

            modelBuilder.Entity("Attendance.API.Models.EmployeeAttendance", b =>
                {
                    b.HasOne("Attendance.API.Models.Employee", "Employee")
                        .WithOne("EmployeeAttendance")
                        .HasForeignKey("Attendance.API.Models.EmployeeAttendance", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Attendance.API.Models.Employee", b =>
                {
                    b.Navigation("EmployeeAttendance");
                });
#pragma warning restore 612, 618
        }
    }
}
